# Generated by Django 5.2.1 on 2025-07-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('locality_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('locality_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('device_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='zws2.city')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rain_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rain_accumulation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aqi_pm_10', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('aqi_pm_2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('locality_id', models.ForeignKey(db_column='locality_id', on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='zws2.station')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['latitude', 'longitude'], name='zws2_statio_latitud_09bbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['locality_id', 'fetched_at'], name='zws2_weathe_localit_a59951_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['fetched_at'], name='zws2_weathe_fetched_8dffb6_idx'),
        ),
    ]
